const DIGITS = "0123456789";
const LETTERS = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_";
const LETTERS_DIGITS = LETTERS + DIGITS;

export default { DIGITS, LETTERS, LETTERS_DIGITS };
