export default Object.freeze({
	SET: "set",
	FUNC: "func",
	IF: "if",
	ELSE: "else",
	FOR: "for",
	TO: "to",
	INC: "inc",
	WHILE: "while",
	RETURN: "return",
	CONTINUE: "continue",
	BREAK: "break",
	TRUE: "true",
	FALSE: "false",
	NULL: "null",
	NAN: "NaN",
	EACH: "each",
	TYPE: "type",
	INCLUDE: "include",
	WAITFOR: "waitfor",
	IN: "in",
});
